# Generated by Django 3.2.3 on 2021-06-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manager', '0009_alter_userratebook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='userratebook',
            name='avg_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
