# Generated by Django 3.2.3 on 2021-05-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places_in_room', models.PositiveSmallIntegerField()),
                ('count_per_nigth', models.PositiveIntegerField()),
                ('is_free', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
