# Generated by Django 3.2.3 on 2021-05-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='count_per_nigth',
            new_name='count_per_night',
        ),
        migrations.AlterField(
            model_name='room',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
