# Generated by Django 3.2.3 on 2021-05-25 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room', '0004_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='owners',
            name='add_to',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
