# Generated by Django 3.2.3 on 2021-05-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room', '0005_owners_add_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='add_to',
            field=models.DateField(),
        ),
    ]
