# Generated by Django 3.2.3 on 2021-05-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room', '0006_alter_owners_add_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owners',
            name='add_to',
        ),
    ]
