# Generated by Django 3.2.3 on 2021-05-25 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room', '0007_remove_owners_add_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='owners',
            name='add_to',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
