# Generated by Django 3.2.3 on 2021-05-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room', '0008_owners_add_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.PositiveSmallIntegerField()),
                ('cleanness', models.PositiveSmallIntegerField()),
                ('personal', models.PositiveSmallIntegerField()),
                ('eat', models.PositiveSmallIntegerField()),
                ('entertainment', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
