# Generated by Django 3.2.3 on 2021-06-02 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room', '0009_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_free',
        ),
        migrations.AddField(
            model_name='owners',
            name='add_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owners',
            name='add_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hotel_room.owners')),
            ],
        ),
    ]
